const els={form:document.querySelector('#search-form'),input:document.querySelector('#book-search'),status:document.querySelector('#status'),results:document.querySelector('#results'),grid:document.querySelector('#book-grid'),count:document.querySelector('#result-count'),soundtrack:document.querySelector('#soundtrack'),title:document.querySelector('#selected-title'),meta:document.querySelector('#selected-meta'),moods:document.querySelector('#mood-strip'),tracks:document.querySelector('#tracks'),rebuild:document.querySelector('#rebuild'),audio:document.querySelector('#audio'),play:document.querySelector('#play'),prev:document.querySelector('#prev'),next:document.querySelector('#next'),art:document.querySelector('#now-art'),nowTrack:document.querySelector('#now-track'),nowArtist:document.querySelector('#now-artist'),youtubeExport:document.querySelector('#youtube-export'),exportStatus:document.querySelector('#export-status'),playlistResult:document.querySelector('#playlist-result')};
const state={book:null,tracks:[],current:-1,musicCache:new Map(),bookCache:new Map(),youtubeCache:new Map(),youtubeIds:[],youtubeMatches:[]};
const THEME_RULES={fantasy:['soundtrack','classical','folk','world','new age'],adventure:['soundtrack','alternative','rock','world'],mystery:['jazz','ambient','soundtrack','electronic'],thriller:['electronic','ambient','soundtrack','alternative'],horror:['soundtrack','ambient','metal','dark ambient'],romance:['singer/songwriter','jazz','pop','classical'],love:['singer/songwriter','jazz','pop'],war:['soundtrack','classical','folk','rock'],history:['classical','folk','world','soundtrack'],historical:['classical','folk','world','soundtrack'],mythology:['world','folk','soundtrack','classical'],magic:['new age','soundtrack','electronic','classical'],science:['electronic','ambient','classical'],science_fiction:['electronic','ambient','soundtrack'],dystopia:['electronic','alternative','ambient','industrial'],nature:['ambient','folk','world','new age'],travel:['world','folk','alternative'],survival:['ambient','soundtrack','rock'],coming_of_age:['indie rock','alternative','pop','singer/songwriter'],friendship:['indie rock','pop','alternative'],family:['singer/songwriter','pop','classical'],philosophy:['ambient','classical','jazz'],religion:['world','classical','ambient'],politics:['folk','rock','alternative','classical'],crime:['jazz','soundtrack','electronic','hip-hop/rap'],detective:['jazz','soundtrack','ambient'],school:['indie rock','pop','alternative'],humor:['pop','jazz','alternative'],comedy:['pop','jazz','alternative'],literary:['classical','jazz','ambient','singer/songwriter'],poetry:['ambient','classical','jazz','singer/songwriter'],biography:['folk','singer/songwriter','classical'],memoir:['folk','singer/songwriter','ambient'],psychology:['ambient','classical','jazz'],political:['folk','rock','classical'],family_life:['singer/songwriter','folk','classical']};
const STOPWORDS=new Set('the a an and or of to in on for with from by into about after before over under this that these those is are was were be been book books novel story stories edition volume part life man woman men women one two three four five'.split(' '));
const GENRE_FALLBACK=['ambient','classical','soundtrack'];
const TITLE_HINTS=[
  {re:/lord of the rings|hobbit|tolkien|middle earth|dragon|wizard|witch|fairy|fantasy/i,genres:['folk','soundtrack','classical','world'],terms:['fantasy','adventure','magic']},
  {re:/dune|foundation|neuromancer|mars|robot|galaxy|space|expanse|three-body/i,genres:['electronic','ambient','soundtrack'],terms:['science fiction','space','future']},
  {re:/sherlock|poirot|murder|detective|mystery|agatha christie/i,genres:['jazz','soundtrack','classical'],terms:['mystery','detective','crime']},
  {re:/dracula|frankenstein|haunting|horror|carrie|shining|salem/i,genres:['ambient','soundtrack','metal'],terms:['horror','dark']},
  {re:/pride and prejudice|jane eyre|wuthering|sense and sensibility|romance/i,genres:['classical','jazz','singer/songwriter'],terms:['romance','love','relationship']}
];
const GENRE_STOP=new Set(['music','rock','pop','alternative','electronic','classical','ambient','soundtrack','folk','world','jazz','metal','new age','singer/songwriter','indie rock','hip-hop/rap']);
const YOUTUBE_INSTANCES=['https://inv.nadeko.net','https://invidious.nerdvpn.de'];
const YOUTUBE_PENALTIES=[/karaoke/i,/tribute/i,/cover/i,/nightcore/i,/slowed/i,/sped\s*up/i,/8d/i,/10\s*hours?/i,/reaction/i,/review/i,/remix/i,/live/i,/concert/i,/full\s*album/i,/playlist/i];
const YOUTUBE_BOOSTS=[/official audio/i,/official video/i,/official music video/i,/lyrics?/i,/audio/i,/topic/i,/vevo/i];
function setStatus(msg='',error=false){els.status.textContent=msg;els.status.classList.toggle('error',error)}
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function coverUrl(id){return id?`https://covers.openlibrary.org/b/id/${id}-M.jpg`:''}
function normalizeWords(text=''){return text.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOPWORDS.has(w))}
function bookThemes(book){const raw=[...(book.subject_key||[]),...(book.subject||[])].map(x=>String(x).toLowerCase().replace(/[^a-z0-9_ ]/g,'_')).map(x=>x.replace(/\s+/g,'_')).filter(Boolean);const strong=raw.filter(x=>!['fiction','literature','general','accessible_book','protected_da_content'].includes(x)&&!/^\d+(_|$)/.test(x));return [...new Set(strong)].slice(0,24)}
function themeTerms(themes){return [...new Set(themes.flatMap(t=>t.replace(/_/g,' ').split(/\s+/)).filter(w=>w.length>3&&!STOPWORDS.has(w)))]}
function chooseProfile(book,themes){const scores=new Map();const terms=themeTerms(themes);for(const theme of themes){for(const [needle,genres] of Object.entries(THEME_RULES)){if(theme.includes(needle))genres.forEach((g,i)=>scores.set(g,(scores.get(g)||0)+(7-i*1.2)))}}const title=`${book.title} ${(book.author_name||[]).join(' ')}`;for(const hint of TITLE_HINTS){if(hint.re.test(title)){hint.genres.forEach((g,i)=>scores.set(g,(scores.get(g)||0)+(10-i)));terms.push(...hint.terms)}}const ranked=[...scores.entries()].sort((a,b)=>b[1]-a[1]).map(([g])=>g);const genres=[...new Set([...ranked,...GENRE_FALLBACK])].slice(0,4);return {terms:[...new Set(terms)].slice(0,18),genres}}
async function openLibrarySearch(q){const key=q.trim().toLowerCase();if(state.bookCache.has(key))return state.bookCache.get(key);const url=`https://openlibrary.org/search.json?q=${encodeURIComponent(q)}&fields=key,title,author_name,first_publish_year,cover_i,subject,subject_key&limit=8`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Open Library search failed.');const data=await res.json();const docs=(data.docs||[]).filter(x=>x.title);state.bookCache.set(key,docs);return docs}
function renderBooks(books){els.grid.innerHTML='';els.count.textContent=`${books.length} found`;els.results.hidden=false;books.forEach(book=>{const card=document.createElement('article');card.className='book';const btn=document.createElement('button');btn.type='button';const cover=coverUrl(book.cover_i);btn.innerHTML=`<div class="cover">${cover?`<img loading="lazy" src="${cover}" alt="Cover of ${esc(book.title)}">`:`<div class="cover-fallback">${esc(book.title.slice(0,28))}</div>`}</div><div class="book-info"><div class="book-title">${esc(book.title)}</div><div class="book-author">${esc((book.author_name||[]).slice(0,2).join(', '))}</div><div class="book-year">${book.first_publish_year||'Unknown year'}</div></div>`;btn.addEventListener('click',()=>selectBook(book));card.appendChild(btn);els.grid.appendChild(card)})}
async function iTunesSearch(term){const key=term.toLowerCase();if(state.musicCache.has(key))return state.musicCache.get(key);const params=new URLSearchParams({term,media:'music',entity:'song',country:'US',limit:'25',explicit:'No'});const res=await fetch(`https://itunes.apple.com/search?${params}`);if(!res.ok)throw new Error('Music search failed.');const data=await res.json();const tracks=(data.results||[]).filter(t=>t.previewUrl&&t.trackName&&t.artistName);state.musicCache.set(key,tracks);return tracks}
function scoreTrack(track,profile){const title=`${track.trackName||''} ${track.collectionName||''}`.toLowerCase();const artist=(track.artistName||'').toLowerCase();const genre=(track.primaryGenreName||'').toLowerCase();let score=0;profile.terms.forEach(term=>{const t=term.toLowerCase();if(title.includes(t))score+=14;if(artist.includes(t))score+=5;if(genre.includes(t))score+=4});profile.genres.forEach((g,i)=>{if(genre===g||genre.includes(g)||g.includes(genre))score+=Math.max(1,9-i*2)});if(/soundtrack|classical|ambient|folk|world|jazz/i.test(genre))score+=2;if(GENRE_STOP.has(genre)&&!profile.genres.includes(genre))score-=2;if(/karaoke|tribute|cover version|greatest hits|remix|instrumental version|live version/i.test(title))score-=7;if(/christmas|holiday/i.test(title)&&!profile.terms.some(t=>/christmas|holiday/.test(t)))score-=20;return score}
function explainTrack(track,profile){const genre=(track.primaryGenreName||'music').toLowerCase();const matched=profile.terms.find(t=>`${track.trackName} ${track.collectionName} ${track.artistName}`.toLowerCase().includes(t.toLowerCase()));if(matched)return `theme: ${matched.replace(/_/g,' ')}`;const genreMatch=profile.genres.find(g=>genre.includes(g)||g.includes(genre));return genreMatch?`mood: ${genreMatch}`:'overall atmosphere'}
async function buildSoundtrack(book){setStatus('Reading the book’s themes…');const themes=bookThemes(book);const profile=chooseProfile(book,themes);const queryTerms=[book.title,...profile.genres.map(g=>`${profile.terms.slice(0,2).join(' ')} ${g}`)];const queries=[...new Set(queryTerms)].slice(0,4);setStatus('Finding music that fits…');const buckets=await Promise.all(queries.map(q=>iTunesSearch(q).catch(()=>[])));const unique=new Map();buckets.flat().forEach(t=>{if(!unique.has(t.trackId))unique.set(t.trackId,t)});let tracks=[...unique.values()].map(t=>({...t,score:scoreTrack(t,profile),reason:explainTrack(t,profile)})).sort((a,b)=>b.score-a.score);const threshold=tracks.length?Math.max(2,tracks[0].score-9):0;tracks=tracks.filter(t=>t.score>=threshold).slice(0,14);if(!tracks.length)throw new Error('No strong music matches came back. Try another book.');state.book=book;state.tracks=tracks;state.current=-1;state.youtubeIds=[];state.youtubeMatches=[];els.title.textContent=book.title;els.meta.textContent=`${(book.author_name||[]).slice(0,2).join(', ')||'Unknown author'} · ${book.first_publish_year||'year unknown'}`;els.moods.innerHTML=(themes.length?themes.filter(t=>!GENRE_STOP.has(t)).slice(0,8):['story']).map(t=>`<span class="mood">${esc(t.replace(/_/g,' '))}</span>`).join('');els.youtubeExport.disabled=!tracks.length;els.playlistResult.hidden=true;els.playlistResult.innerHTML='';renderTracks();els.soundtrack.hidden=false;els.soundtrack.scrollIntoView({behavior:'smooth',block:'start'});setStatus('')}
function renderTracks(){els.tracks.innerHTML=state.tracks.map((t,i)=>{const match=state.youtubeMatches.find(m=>m.trackId===t.trackId);return `<div class="track ${i===state.current?'playing':''}" data-i="${i}"><div class="track-num">${String(i+1).padStart(2,'0')}</div><div class="track-copy"><div class="track-title">${esc(t.trackName)}</div><div class="track-artist">${esc(t.artistName)} · ${esc(t.primaryGenreName||'music')}</div></div><div class="track-score">${esc(match?'YouTube match':'')||esc(t.reason)}</div><button class="track-play" type="button">Preview</button></div>`}).join('');els.tracks.querySelectorAll('.track').forEach(row=>row.querySelector('button').addEventListener('click',()=>playIndex(Number(row.dataset.i))))}
function updatePlayer(){const t=state.tracks[state.current];if(!t){els.nowTrack.textContent='Choose a track';els.nowArtist.textContent='30-second sample';els.art.textContent='♪';return}els.nowTrack.textContent=t.trackName;els.nowArtist.textContent=t.artistName;els.art.innerHTML=t.artworkUrl100?`<img src="${t.artworkUrl100}" alt="" style="width:100%;height:100%;object-fit:cover;border-radius:12px">`:'♪';renderTracks()}
function playIndex(i){const t=state.tracks[i];if(!t)return;state.current=i;els.audio.src=t.previewUrl;els.audio.play().catch(()=>{});els.play.textContent='❚❚';updatePlayer()}
function pause(){els.audio.pause();els.play.textContent='▶'}function nextTrack(){if(state.tracks.length)playIndex((state.current+1)%state.tracks.length)}
function normalizeYT(value){return String(value||'').toLowerCase().replace(/&amp;/g,'&').replace(/[^a-z0-9]+/g,' ').trim()}
function youtubeCandidateScore(video,track){const title=normalizeYT(video.title);const author=normalizeYT(video.author);const wantedTitle=normalizeYT(track.trackName);const wantedArtist=normalizeYT(track.artistName);let score=0;if(title===wantedTitle)score+=30;if(title.includes(wantedTitle))score+=22;else if(wantedTitle.includes(title))score+=10;const words=normalizeWords(track.trackName);words.forEach(w=>{if(title.includes(w))score+=3});const artistWords=normalizeWords(track.artistName);artistWords.forEach(w=>{if(title.includes(w))score+=3;if(author.includes(w))score+=4});YOUTUBE_BOOSTS.forEach(re=>{if(re.test(video.title||''))score+=6});YOUTUBE_PENALTIES.forEach(re=>{if(re.test(video.title||''))score-=12});if(/music/i.test(video.type||''))score+=1;return score}
async function youtubeSearch(term){const key=term.toLowerCase();if(state.youtubeCache.has(key))return state.youtubeCache.get(key);let lastError=null;for(const base of YOUTUBE_INSTANCES){try{const url=`${base}/api/v1/search?q=${encodeURIComponent(term)}&type=video&region=US`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error(`YouTube search ${res.status}`);const data=await res.json();const items=(Array.isArray(data)?data:[]).filter(x=>x.type==='video'&&x.videoId&&x.title);state.youtubeCache.set(key,items);return items}catch(err){lastError=err}}throw lastError||new Error('YouTube search unavailable.')}
async function findYouTubeMatches(){const matches=[];for(let i=0;i<state.tracks.length;i++){const track=state.tracks[i];setStatus(`Finding YouTube audio ${i+1} of ${state.tracks.length}…`);const queries=[`"${track.trackName}" "${track.artistName}" official audio`,`"${track.trackName}" "${track.artistName}"`];let candidates=[];for(const q of queries){try{candidates.push(...await youtubeSearch(q))}catch{}}const unique=[...new Map(candidates.map(v=>[v.videoId,v])).values()];if(unique.length){unique.sort((a,b)=>youtubeCandidateScore(b,track)-youtubeCandidateScore(a,track));const best=unique[0];matches.push({trackId:track.trackId,videoId:best.videoId,title:best.title,author:best.author,url:`https://www.youtube.com/watch?v=${best.videoId}`})}}state.youtubeMatches=matches;state.youtubeIds=matches.map(m=>m.videoId);renderTracks();return matches}
function youtubeQueueUrl(ids){return `https://www.youtube.com/watch_videos?video_ids=${ids.join(',')}`}
function fallbackYouTubeSearchUrl(track){return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${track.trackName} ${track.artistName}`)}`}
async function createYouTubeQueue(){if(!state.tracks.length)return;els.youtubeExport.disabled=true;els.playlistResult.hidden=true;setStatus('Building a no-login YouTube playlist…');const matches=await findYouTubeMatches();if(!matches.length){els.youtubeExport.disabled=false;throw new Error('YouTube search could not find the soundtrack right now. Try again in a moment.')}const url=youtubeQueueUrl(state.youtubeIds);const missing=state.tracks.filter(t=>!matches.some(m=>m.trackId===t.trackId));els.playlistResult.innerHTML=`<strong>✓ YouTube playlist ready — ${matches.length} of ${state.tracks.length} songs found.</strong><span>No YouTube login is needed. This opens as a YouTube queue/temporary playlist rather than saving a playlist to an account.</span><a href="${url}" target="_blank" rel="noopener">Open all songs in YouTube ↗</a>${missing.length?`<div class="playlist-missing"><small>Not matched automatically:</small>${missing.map(t=>`<a href="${fallbackYouTubeSearchUrl(t)}" target="_blank" rel="noopener">${esc(t.trackName)} — search YouTube ↗</a>`).join('')}</div>`:''}`;els.playlistResult.hidden=false;els.youtubeExport.disabled=false;setStatus('')}
function selectBook(book){buildSoundtrack(book).catch(err=>setStatus(err.message||'Could not build soundtrack.',true))}
els.form.addEventListener('submit',async e=>{e.preventDefault();const q=els.input.value.trim();if(!q)return;setStatus('Searching Open Library…');els.results.hidden=true;els.soundtrack.hidden=true;try{const books=await openLibrarySearch(q);if(!books.length){setStatus('No books found. Try a different title.',true);return}renderBooks(books);setStatus('')}catch(err){setStatus(err.message||'Search failed.',true)}});
els.rebuild.addEventListener('click',()=>{if(state.book)buildSoundtrack(state.book).catch(err=>setStatus(err.message||'Could not rebuild.',true))});
els.play.addEventListener('click',()=>{if(els.audio.paused){if(state.current<0&&state.tracks.length)playIndex(0);else els.audio.play().catch(()=>{})}else pause()});
els.audio.addEventListener('play',()=>els.play.textContent='❚❚');els.audio.addEventListener('pause',()=>els.play.textContent='▶');els.audio.addEventListener('ended',nextTrack);els.prev.addEventListener('click',()=>{if(state.tracks.length)playIndex((state.current-1+state.tracks.length)%state.tracks.length)});els.next.addEventListener('click',nextTrack);els.youtubeExport.addEventListener('click',()=>createYouTubeQueue().catch(err=>setStatus(err.message||'Could not create YouTube playlist.',true)));
