const els={form:document.querySelector('#search-form'),input:document.querySelector('#book-search'),status:document.querySelector('#status'),results:document.querySelector('#results'),grid:document.querySelector('#book-grid'),count:document.querySelector('#result-count'),soundtrack:document.querySelector('#soundtrack'),title:document.querySelector('#selected-title'),meta:document.querySelector('#selected-meta'),moods:document.querySelector('#mood-strip'),tracks:document.querySelector('#tracks'),rebuild:document.querySelector('#rebuild'),audio:document.querySelector('#audio'),play:document.querySelector('#play'),prev:document.querySelector('#prev'),next:document.querySelector('#next'),art:document.querySelector('#now-art'),nowTrack:document.querySelector('#now-track'),nowArtist:document.querySelector('#now-artist'),youtubeExport:document.querySelector('#youtube-export'),exportStatus:document.querySelector('#export-status'),playlistResult:document.querySelector('#playlist-result')};
const state={book:null,tracks:[],current:-1,musicCache:new Map(),bookCache:new Map(),youtubeCache:new Map(),youtubeMatches:[]};
const YOUTUBE_API_KEY=String(window.READSOUND_YOUTUBE_API_KEY||'').trim();
const THEME_RULES={fantasy:['soundtrack','classical','folk','world','new age'],adventure:['soundtrack','folk','world','rock'],mystery:['ambient','jazz','soundtrack','electronic'],thriller:['ambient','electronic','soundtrack'],horror:['ambient','soundtrack','classical'],romance:['classical','jazz','piano','soundtrack'],love:['piano','jazz','classical'],war:['soundtrack','classical','folk'],history:['classical','folk','world','soundtrack'],historical:['classical','folk','world','soundtrack'],mythology:['world','folk','soundtrack','classical'],magic:['new age','soundtrack','classical','ambient'],science:['electronic','ambient','classical'],science_fiction:['electronic','ambient','soundtrack'],dystopia:['electronic','ambient','industrial'],nature:['ambient','folk','world','new age'],travel:['world','folk','ambient'],survival:['ambient','soundtrack','rock'],coming_of_age:['indie rock','alternative','piano'],friendship:['indie rock','acoustic','piano'],family:['piano','classical','acoustic'],philosophy:['ambient','classical','jazz'],religion:['classical','world','ambient'],politics:['folk','classical','rock'],crime:['jazz','soundtrack','ambient'],detective:['jazz','soundtrack','classical'],school:['piano','indie rock','classical'],humor:['piano','jazz','acoustic'],comedy:['piano','jazz','acoustic'],biography:['piano','folk','acoustic'],memoir:['piano','folk','ambient'],psychology:['ambient','piano','classical']};
const STOPWORDS=new Set('the a an and or of to in on for with from by into about after before over under this that these those is are was were be been book books novel story stories edition volume part life man woman men women one two three four five six seven eight nine ten author authors works literature literary fiction fictional history historical general accessible protected da'.split(' '));
const NOISE=new Set(['british','english','irish','american','canadian','australian','scottish','welsh','french','german','european','literature','literary','fiction','fictional','criticism','critic','textual','text','language','languages','history','century','twentieth','nineteenth','twentyfirst','authors','author','works','working','accessible','protected','da','general']);
const GENRE_STOP=new Set(['music','rock','pop','alternative','electronic','classical','ambient','soundtrack','folk','world','jazz','metal','new age','singer/songwriter','indie rock','hip-hop/rap','piano','acoustic']);
const TITLE_HINTS=[
 {re:/lord of the rings|hobbit|tolkien|middle earth|dragon|wizard|witch|fairy|fantasy/i,genres:['folk','soundtrack','classical','world'],terms:['fantasy','adventure','magic']},
 {re:/dune|foundation|neuromancer|mars|robot|galaxy|space|expanse|three-body/i,genres:['electronic','ambient','soundtrack'],terms:['science fiction','space','future']},
 {re:/sherlock|poirot|murder|detective|mystery|agatha christie/i,genres:['jazz','soundtrack','classical'],terms:['mystery','detective','crime']},
 {re:/dracula|frankenstein|haunting|horror|carrie|shining|salem/i,genres:['ambient','soundtrack','classical'],terms:['horror','dark']},
 {re:/pride and prejudice|jane eyre|wuthering|sense and sensibility|romance/i,genres:['classical','piano','jazz'],terms:['romance','love','relationship']}
];
const VOCAL_RE=/\b(vocal|vocals|lyrics?|singer|singing|song|performed by|feat\.?|featuring|with vocals|spoken word|choir|chorus|rap|mc|band version)\b/i;
const INSTRUMENTAL_RE=/\b(instrumental|piano|orchestral|orchestra|score|soundtrack|ambient|acoustic|guitar|strings|violin|cello|saxophone|jazz|classical|study|background)\b/i;
const YOUTUBE_BAD=/karaoke|tribute|cover|nightcore|slowed|sped\s*up|8d|10\s*hours?|reaction|review|remix|mashup|concert|live\s*(concert|performance)?|full\s*album|playlist|fan[- ]?made|ai[- ]?cover|lyrics?|vocal/i;
const YOUTUBE_GOOD=/official\s*(audio|video|music\s*video)?|audio|instrumental|soundtrack|score|topic|vevo/i;
function setStatus(msg='',error=false){els.status.textContent=msg;els.status.classList.toggle('error',error)}
function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function coverUrl(id){return id?`https://covers.openlibrary.org/b/id/${id}-M.jpg`:''}
function normalize(value=''){return String(value).toLowerCase().replace(/&amp;/g,'&').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function words(text=''){return normalize(text).split(' ').filter(w=>w.length>2&&!STOPWORDS.has(w))}
function cleanTheme(value){const n=String(value||'').toLowerCase().replace(/[^a-z0-9_ ]/g,'_').replace(/\s+/g,'_').replace(/^_+|_+$/g,'');if(!n||NOISE.has(n)||/^\d+(_|$)/.test(n))return '';if(n.includes('history_and_criticism')||n.includes('literature_history')||n.includes('literary_criticism')||n.includes('fictional_works')||n.includes('works_by_one_author'))return '';return n}
function bookThemes(book){const raw=[...(book.subject_key||[]),...(book.subject||[])].map(cleanTheme).filter(Boolean);return [...new Set(raw)].slice(0,30)}
function themeTerms(themes){return [...new Set(themes.flatMap(t=>t.replace(/_/g,' ').split(/\s+/)).filter(w=>w.length>3&&!STOPWORDS.has(w)&&!NOISE.has(w)))];}
function chooseProfile(book,themes){const scores=new Map();const terms=themeTerms(themes);for(const theme of themes){for(const [needle,genres] of Object.entries(THEME_RULES)){if(theme.includes(needle))genres.forEach((g,i)=>scores.set(g,(scores.get(g)||0)+(7-i*1.2)))}}const title=`${book.title} ${(book.author_name||[]).join(' ')}`;for(const hint of TITLE_HINTS){if(hint.re.test(title)){hint.genres.forEach((g,i)=>scores.set(g,(scores.get(g)||0)+(12-i*1.5)));terms.push(...hint.terms)}}const ranked=[...scores.entries()].sort((a,b)=>b[1]-a[1]).map(([g])=>g);return {terms:[...new Set(terms)].slice(0,20),genres:[...new Set([...ranked,'ambient','classical','soundtrack','piano','folk'])].slice(0,5)}}
async function openLibrarySearch(q){const key=q.trim().toLowerCase();if(state.bookCache.has(key))return state.bookCache.get(key);const url=`https://openlibrary.org/search.json?q=${encodeURIComponent(q)}&fields=key,title,author_name,first_publish_year,cover_i,subject,subject_key&limit=8`;const res=await fetch(url,{headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Open Library search failed.');const data=await res.json();const docs=(data.docs||[]).filter(x=>x.title);state.bookCache.set(key,docs);return docs}
function renderBooks(books){els.grid.innerHTML='';els.count.textContent=`${books.length} found`;els.results.hidden=false;books.forEach(book=>{const card=document.createElement('article');card.className='book';const btn=document.createElement('button');btn.type='button';const cover=coverUrl(book.cover_i);btn.innerHTML=`<div class="cover">${cover?`<img loading="lazy" src="${cover}" alt="Cover of ${esc(book.title)}">`:`<div class="cover-fallback">${esc(book.title.slice(0,28))}</div>`}</div><div class="book-info"><div class="book-title">${esc(book.title)}</div><div class="book-author">${esc((book.author_name||[]).slice(0,2).join(', '))}</div><div class="book-year">${book.first_publish_year||'Unknown year'}</div></div>`;btn.addEventListener('click',()=>selectBook(book));card.appendChild(btn);els.grid.appendChild(card)})}
async function iTunesSearch(term){const key=term.toLowerCase();if(state.musicCache.has(key))return state.musicCache.get(key);const params=new URLSearchParams({term,media:'music',entity:'song',country:'US',limit:'50',explicit:'No'});const res=await fetch(`https://itunes.apple.com/search?${params}`);if(!res.ok)throw new Error('Music search failed.');const data=await res.json();const tracks=(data.results||[]).filter(t=>t.previewUrl&&t.trackName&&t.artistName);state.musicCache.set(key,tracks);return tracks}
function instrumentalScore(t){const text=`${t.trackName||''} ${t.collectionName||''} ${t.artistName||''}`;let s=0;if(INSTRUMENTAL_RE.test(text))s+=10;if(/instrumental/i.test(text))s+=18;if(/piano|orchestral|orchestra|score|soundtrack|ambient|classical|acoustic|strings|violin|cello/i.test(text))s+=6;if(VOCAL_RE.test(text))s-=30;if(/karaoke|tribute|cover|remix|live|greatest hits|holiday|christmas/i.test(text))s-=18;return s}
function scoreTrack(t,p){const title=normalize(`${t.trackName||''} ${t.collectionName||''}`),artist=normalize(t.artistName||''),genre=normalize(t.primaryGenreName||'');let score=instrumentalScore(t);p.terms.forEach(term=>{const q=normalize(term);if(q.length>3&&title.includes(q))score+=13;if(q.length>3&&artist.includes(q))score+=4;if(q.length>3&&genre.includes(q))score+=3});p.genres.forEach((g,i)=>{const q=normalize(g);if(genre===q||genre.includes(q)||q.includes(genre))score+=Math.max(1,9-i*1.5)});if(/soundtrack|classical|ambient|folk|world|jazz/i.test(genre))score+=3;return score}
function explainTrack(t,p){if(/instrumental/i.test(`${t.trackName} ${t.collectionName}`))return 'instrumental';const genre=normalize(t.primaryGenreName||'music');const gm=p.genres.find(g=>genre.includes(normalize(g))||normalize(g).includes(genre));return gm?`mood: ${gm}`:'instrumental atmosphere'}
async function buildSoundtrack(book){setStatus('Reading the book’s themes…');const themes=bookThemes(book);const p=chooseProfile(book,themes);const themed=(p.terms.length?p.terms.slice(0,4).join(' '):'cinematic').trim();const queryPool=[`${book.title} instrumental soundtrack`,`${themed} instrumental`,`${themed} cinematic instrumental`,`piano ${themed} instrumental`,...p.genres.slice(0,3).map(g=>`${g} instrumental`),'cinematic instrumental','orchestral instrumental','piano instrumental','ambient instrumental'];const queries=[...new Set(queryPool)].slice(0,8);setStatus('Finding instrumental music that fits…');const buckets=await Promise.all(queries.map(q=>iTunesSearch(q).catch(()=>[])));const unique=new Map();buckets.flat().forEach(t=>{if(!unique.has(t.trackId))unique.set(t.trackId,t)});let ranked=[...unique.values()].map(t=>({...t,score:scoreTrack(t,p),reason:explainTrack(t,p)})).filter(t=>t.score>=4).sort((a,b)=>b.score-a.score);const seen=new Set();ranked=ranked.filter(t=>{const k=normalize(`${t.trackName} ${t.artistName}`);if(seen.has(k))return false;seen.add(k);return true});ranked=ranked.slice(0,12);if(!ranked.length)throw new Error('I could not find instrumental music for that book. Try another edition or rebuild.');state.book=book;state.tracks=ranked;state.current=-1;state.youtubeMatches=[];els.title.textContent=book.title;els.meta.textContent=`${(book.author_name||[]).slice(0,2).join(', ')||'Unknown author'} · ${book.first_publish_year||'year unknown'}`;els.moods.innerHTML=(themes.length?themes.filter(t=>!GENRE_STOP.has(t)).slice(0,8):['instrumental']).map(t=>`<span class="mood">${esc(t.replace(/_/g,' '))}</span>`).join('');els.youtubeExport.disabled=!ranked.length;els.playlistResult.hidden=true;els.playlistResult.innerHTML='';renderTracks();els.soundtrack.hidden=false;els.soundtrack.scrollIntoView({behavior:'smooth',block:'start'});setStatus('')}
function renderTracks(){els.tracks.innerHTML=state.tracks.map((t,i)=>`<div class="track ${i===state.current?'playing':''}" data-i="${i}"><div class="track-num">${String(i+1).padStart(2,'0')}</div><div class="track-copy"><div class="track-title">${esc(t.trackName)}</div><div class="track-artist">${esc(t.artistName)} · ${esc(t.primaryGenreName||'music')} · instrumental</div></div><div class="track-score">${esc(state.youtubeMatches.find(m=>m.trackId===t.trackId)?'YouTube match':t.reason)}</div><button class="track-play" type="button">Preview</button></div>`).join('');els.tracks.querySelectorAll('.track').forEach(row=>row.querySelector('button').addEventListener('click',()=>playIndex(Number(row.dataset.i))))}
function updatePlayer(){const t=state.tracks[state.current];if(!t){els.nowTrack.textContent='Choose a track';els.nowArtist.textContent='Instrumental preview';els.art.textContent='♪';return}els.nowTrack.textContent=t.trackName;els.nowArtist.textContent=`${t.artistName} · instrumental`;els.art.innerHTML=t.artworkUrl100?`<img src="${t.artworkUrl100}" alt="" style="width:100%;height:100%;object-fit:cover;border-radius:12px">`:'♪';renderTracks()}
function playIndex(i){const t=state.tracks[i];if(!t)return;state.current=i;els.audio.src=t.previewUrl;els.audio.play().catch(()=>{});els.play.textContent='❚❚';updatePlayer()}
function pause(){els.audio.pause();els.play.textContent='▶'}
function nextTrack(){if(state.tracks.length)playIndex((state.current+1)%state.tracks.length)}
async function youtubeSearch(term){if(!YOUTUBE_API_KEY||/PASTE_YOUR_/i.test(YOUTUBE_API_KEY))return [];const key=term.toLowerCase();if(state.youtubeCache.has(key))return state.youtubeCache.get(key);const params=new URLSearchParams({part:'snippet',q:term,type:'video',maxResults:'10',regionCode:'US',videoCategoryId:'10',videoEmbeddable:'true',safeSearch:'moderate',key:YOUTUBE_API_KEY});const res=await fetch(`https://www.googleapis.com/youtube/v3/search?${params}`);if(!res.ok){let msg='YouTube search failed.';try{const data=await res.json();msg=data.error?.message||msg}catch{}throw new Error(msg)}const data=await res.json();const out=(data.items||[]).filter(x=>x.id?.videoId&&x.snippet?.title).map(x=>({videoId:x.id.videoId,title:x.snippet.title,author:x.snippet.channelTitle||''}));state.youtubeCache.set(key,out);return out}
function youtubeCandidateScore(v,t){const title=normalize(v.title),author=normalize(v.author),wanted=normalize(t.trackName),artistWords=words(t.artistName),titleWords=words(t.trackName);let s=0;if(title===wanted)s+=50;else if(title.includes(wanted))s+=34;titleWords.forEach(w=>{if(title.includes(w))s+=4});artistWords.forEach(w=>{if(title.includes(w))s+=6;if(author.includes(w))s+=7});if(INSTRUMENTAL_RE.test(v.title))s+=16;if(/official audio|audio/i.test(v.title))s+=8;if(YOUTUBE_GOOD.test(v.title))s+=4;if(YOUTUBE_BAD.test(v.title))s-=30;return s}
async function findYouTubeMatches(){const fallback=()=>{const terms=state.tracks.map(t=>`${t.trackName} ${t.artistName} instrumental`).slice(0,6).join(' OR ');const url=`https://www.youtube.com/results?search_query=${encodeURIComponent(terms)}`;const win=window.open(url,'_blank','noopener');if(!win)location.href=url;els.exportStatus.textContent='No YouTube API key is configured, so I opened a no-login YouTube search containing several instrumental matches.'};if(!YOUTUBE_API_KEY||/PASTE_YOUR_/i.test(YOUTUBE_API_KEY)){fallback();return []}const matches=[];for(let i=0;i<state.tracks.length;i++){const t=state.tracks[i];setStatus(`Finding YouTube song ${i+1} of ${state.tracks.length}…`);let candidates=[];try{candidates=await youtubeSearch(`${t.trackName} ${t.artistName} instrumental -lyrics -vocal -karaoke -cover -remix`)}catch(err){if(i===0)throw err}if(candidates.length){candidates.sort((a,b)=>youtubeCandidateScore(b,t)-youtubeCandidateScore(a,t));const best=candidates[0];if(youtubeCandidateScore(best,t)>=22)matches.push({trackId:t.trackId,videoId:best.videoId,title:best.title,author:best.author,url:`https://www.youtube.com/watch?v=${best.videoId}`})}}state.youtubeMatches=matches;renderTracks();return matches}
function openQueueFromMatches(matches){if(!matches.length){const q=state.tracks.slice(0,6).map(t=>`${t.trackName} ${t.artistName} instrumental`).join(' OR ');const url=`https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;const win=window.open(url,'_blank','noopener');if(!win)location.href=url;return}const ids=matches.map(m=>m.videoId).join(',');const url=`https://www.youtube.com/watch_videos?video_ids=${encodeURIComponent(ids)}`;const win=window.open(url,'_blank','noopener');if(!win)location.href=url;els.playlistResult.hidden=false;els.playlistResult.innerHTML=`<strong>YouTube queue ready</strong><span>${matches.length} of ${state.tracks.length} instrumental tracks were matched.</span><a href="${url}" target="_blank" rel="noopener">Open the queue again ↗</a>`}
async function openYouTube(){if(!state.tracks.length)return;els.youtubeExport.disabled=true;els.exportStatus.textContent='Matching your soundtrack to YouTube…';try{const matches=await findYouTubeMatches();openQueueFromMatches(matches);els.exportStatus.textContent=matches.length?`Matched ${matches.length} instrumental tracks on YouTube.`:'Opened a YouTube search without requiring a login.'}catch(err){els.exportStatus.textContent=err.message||'YouTube could not be reached.'}finally{els.youtubeExport.disabled=false}}
function selectBook(book){buildSoundtrack(book).catch(err=>setStatus(err.message||'Could not build soundtrack.',true))}
els.form.addEventListener('submit',async e=>{e.preventDefault();const q=els.input.value.trim();if(!q)return;setStatus('Searching Open Library…');try{const books=await openLibrarySearch(q);renderBooks(books);setStatus(books.length?'Select a book below.':'No books found. Try a different title.')}catch(err){setStatus(err.message||'Search failed.',true)}});
els.rebuild.addEventListener('click',()=>state.book&&selectBook(state.book));els.play.addEventListener('click',()=>{if(els.audio.paused){if(state.current<0)playIndex(0);else els.audio.play().catch(()=>{})}else pause()});els.prev.addEventListener('click',()=>{if(state.tracks.length)playIndex((state.current-1+state.tracks.length)%state.tracks.length)});els.next.addEventListener('click',nextTrack);els.audio.addEventListener('ended',nextTrack);els.youtubeExport.addEventListener('click',openYouTube);updatePlayer();
